# Numpy Introduction and usage
## we will use numpy in this jupyter notebook

In [7]:
## One Dimensional Array

In [8]:
import numpy as np

In [9]:
array1=np.array([10,20,30,40,50])

In [10]:
print(array1)

[10 20 30 40 50]


In [11]:
## Two Dimensional Array

In [12]:
array2=np.array([[10,20,30],[40,50,60]])
print(array2)

[[10 20 30]
 [40 50 60]]


In [13]:
## Three Dimensional Array

In [14]:
array3=np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,60]]])
print(array3)

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]


# Write an array: to take marks of 5 students in 3 subjects using Numpy
## Math, English, Chemistry
## [[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]]

In [15]:
mark_subject=np.array([[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]])
print('2D Array Example')
print(mark_subject)

2D Array Example
[[50 45 49]
 [40 42 45]
 [35 40 46]
 [39 40 45]
 [48 40 40]]


# Write an array: to take marks of 4 students in 3 subjects for 2 semerter using Numpy
    ## Students Name are: 'Amit', 'Sha', 'Xi, 'Arif'
    ## Math, English, Chemistry
    ## Two Semester: sem1, sem2
    ## 4*3*2
    ## [[85,88],[78,82][90,95]],[[76,70],[40,45][90,90]],[[80,86],[78,82][90,95]],[[85,88],[78,82][70,90]]]

In [16]:
mark_subject_sem=np.array([[[85,88],[78,82],[90,95]],
                           [[76,70],[40,45],[90,90]],
                           [[80,86],[78,82],[90,95]],
                           [[85,88],[78,82],[70,90]]])

In [17]:
print(mark_subject_sem)

[[[85 88]
  [78 82]
  [90 95]]

 [[76 70]
  [40 45]
  [90 90]]

 [[80 86]
  [78 82]
  [90 95]]

 [[85 88]
  [78 82]
  [70 90]]]


# Mathematical Operation

In [18]:
print(array1)

[10 20 30 40 50]


In [19]:
total=np.sum(array1)

In [20]:
print(total)

150


In [21]:
print('Mean: ',np.mean(array1))

Mean:  30.0


In [22]:
print('Index of max: ',np.argmax(array1))

Index of max:  4


In [23]:
our_arr=np.array([100,200,300,7000,400,500,300,1900,600])
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


In [24]:
## Searching and Sorting Example in 1D array

In [25]:
sorted_arr=np.sort(our_arr)
print('**** Sorted Array ')
print(sorted_arr)

**** Sorted Array 
[ 100  200  300  300  400  500  600 1900 7000]


In [26]:
print('Is there any item greater than 500? : ',np.any(sorted_arr>500))

Is there any item greater than 500? :  True


In [27]:
print('All item greater than 500? : ',np.all(sorted_arr>10))

All item greater than 500? :  True


In [28]:
print('All item greater than 10? : ',np.all(sorted_arr>10))

All item greater than 10? :  True


In [29]:
print('Which item greater than 500? : ',np.where(sorted_arr>500))

Which item greater than 500? :  (array([6, 7, 8]),)


In [30]:
print('All item greater than 500 ')
for num in np.where(sorted_arr>500):
    print (num)

All item greater than 500 
[6 7 8]


In [31]:
print('All item greater than 500 ')
for num in sorted_arr>500:
    print (num)

All item greater than 500 
False
False
False
False
False
False
True
True
True


In [33]:
selected_values=sorted_arr[sorted_arr>500]

In [35]:
for num in sorted_arr[sorted_arr>500]:
    print (num)

600
1900
7000


# Slicing 1D Array

In [43]:
print(sorted_arr)

[ 100  200  300  300  400  500  600 1900 7000]


In [42]:
slice_our_array=sorted_arr[1:3]
print(slice_our_array)

[200 300]


In [ ]:
## Starting from an index and going till last

In [41]:
print(sorted_arr[3:])

[ 300  400  500  600 1900 7000]


In [46]:
print(sorted_arr[:4])

[100 200 300 300]


In [47]:
# Step
# [start: end: step]
# Step: every step element

In [48]:
our_slice=sorted_arr[1:6:2]
print(our_slice)

[200 300 500]


In [54]:
print('Original Array :')
print(sorted_arr)
print('\nEvery Third Element: ')
every_third_element=sorted_arr[::3]
print(every_third_element)


Original Array :
[ 100  200  300  300  400  500  600 1900 7000]

Every Third Element: 
[100 300 600]


In [57]:
print('Original Array :')
print(sorted_arr)
print('\nReverse Array: ')
print(sorted_arr[::-1])

Original Array :
[ 100  200  300  300  400  500  600 1900 7000]

Reverse Array: 
[7000 1900  600  500  400  300  300  200  100]
